### PR TITLE
sigstore-python-conformance: Update wrapper

### PR DESCRIPTION
**Pull request by tetsuo-cpp**

### CODE REVIEW

**Review by woodruffw — DISMISSED** [review]

**Comment by tetsuo-cpp** [comment]
I need to cut a `sigstore-python` release to get the tests passing.

**Comment by woodruffw** [comment]
> I need to cut a `sigstore-python` release to get the tests passing.

Let's do a `2.0.0rc0` for this, since the release will contain a bunch of breaking changes 🙂

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
@tetsuo-cpp LGTM! Needs re-app from you too (since I'm the last pusher).

**Comment by tetsuo-cpp** [comment]
Ah I can't approve since I opened it. :/

**Comment by woodruffw** [comment]
Ugh, this is a silly restriction. Maybe this is something we can get relaxed on the org level?

CC @znewman01 for an additional approval (+ thoughts on maybe loosening this branch protection? I'm not sure it's doing much for us in this instance.)

**Comment by znewman01** [comment]
> Ugh, this is a silly restriction. Maybe this is something we can get relaxed on the org level?

CC @cpanato — any thoughts on this approvals issue?

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
I will check the repo config tomorrow

**Comment by cpanato** [comment]
> > Ugh, this is a silly restriction. Maybe this is something we can get relaxed on the org level?
> 
> CC @cpanato — any thoughts on this approvals issue?

it is a configuration for the branch that block approval if you are the committer of the last push: https://github.com/sigstore/community/blob/main/github-sync/github-data/repositories.yaml#L1602

this is to avoid we self-approval prs
i think was @haydentherapper that enable that.

**Comment by haydentherapper** [comment]
Sorry for the inconvenience, but it was intentional to mitigate insider risk. See https://github.com/sigstore/community/pull/263. Otherwise, a maintainer could modify any open PRs and submit without a second approval.

**Comment by woodruffw** [comment]
@haydentherapper @cpanato thanks for the explanation -- that makes sense!

Do you know if there's some way to refine the restriction here, i.e. to not impose it when the last push is a merge?

I think that's the main source of friction here: the combination of this requirement and the "branch must be up-to-date" requirement means that repos with only 1 or 2 active maintainers need to go through a full review cycle on every branch merge, even for trivial things like Dependabot updates.

(I'd actually argue this presents a (very minor) risk: it means that a maintainer can't merge a Dependabot security update if they accidentally click "Update branch" rather than having Dependabot perform the rebase itself with `@dependabot rebase`).

**Comment by cpanato** [comment]
thanks everyone!

**Pull request merged**
